const ACTIVE_CUSTOMERS_ENDPOINT = "users/customers/";
const ACTIVE_EMPLOYEES_ENDPOINT = "users/employees/";
const APPOINTMENT_ENDPOINT = "appointments/"

export { ACTIVE_CUSTOMERS_ENDPOINT, ACTIVE_EMPLOYEES_ENDPOINT, APPOINTMENT_ENDPOINT };