const ACTIVE_CUSTOMERS_ENDPOINT = "users/customers/";
const ACTIVE_EMPLOYEES_ENDPOINT = "users/employees/";
const MAKE_NEW_APPOINTMENT_ENDPOINT = "appointments/"

export { ACTIVE_CUSTOMERS_ENDPOINT, ACTIVE_EMPLOYEES_ENDPOINT, MAKE_NEW_APPOINTMENT_ENDPOINT };